### ISSUE TITLE
Design Update: Side Menu + arrow functionality

### ISSUE THREAD

**Issue by DylanPDao** [DylanPDao/Pokemon-TCG-Search#14]
## ⚙️ Feature

User can click series instead of set; set will then populate each set in the series.

Arrow functions will still display 8 at a time, but the page count will be changed. Hitting arrow runs another api call instead of getting stored in card data.

## 📐 Plan

Remove hardcoded images to hard coded sets and add event listeners to run api calls for sets

Api search calls reduced to 8 at a time and arrows will increment/decrement page

## 🖼️ Wireframes

<img width="554" alt="Screenshot 2023-05-01 at 3 44 48 PM" src="https://user-images.githubusercontent.com/20610202/235544382-8ccadae9-8297-4078-8ea7-e1483b710066.png">

## ✅ Task List

- [ ] Sidebar changes
    - [ ] delete hardcoded images
    - [ ] add text for each series
    - [ ] on click listener for each series text to populate sets 
    - [ ] each set for series populate image with set id
    - [ ] on click for image renders info on search tab
- [ ] arrow functionality change
    - [ ] change search to max pageCount 8
    - [ ] arrow icons decrement/increment respectively
    - [ ] every arrow press moves next 8 into picture or previous 8
