### ISSUE TITLE
Feature: User can  toggle legal cards

### ISSUE THREAD

**Issue by DylanPDao** [DylanPDao/Pokemon-TCG-Search#16]
## ⚙️ Feature
User can toggle between legal cards only view or all cards

## 📐 Functionality

toggle button at top of page can toggle view for legal cards or illegal

## 🖼️ Wireframes

<img width="747" alt="Screenshot 2023-05-02 at 12 08 10 PM" src="https://user-images.githubusercontent.com/20610202/235762223-545b0bc8-5f11-4797-a9a0-ce24f048ddd6.png">

## ✅ Task List

- [ ] add toggle switch into dom tree
- [ ] Function for toggle
    - [ ] when toggle on (automatic) value set to standard:legal
    - [ ] when toggle off value set to no extra search value
- [ ] add if statement into search functions 
    - [ ] if on change http address to include value
    - [ ] if off http address doesnt have value
- [ ]  style the toggle button
